[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.render]
build-command = "pip install -r requirements.txt"
start-command = "gunicorn render_server:app"
